### ISSUE TITLE
Options to compute g2 for positive time only

### ISSUE THREAD

**Issue by zak489** [GCBallesteros/trattoria#3]
Hi Guillem,

I am currently analyzing the g2 for a time tag file. Since I am looking at delays as long as 1 ms, to save some computing time and memory, is it possible to introduce the "ring" algorithm in the g2 analysis code so that only coincidences at positive times are computed? This was a feature in the readPTU repo. Just wondering if it is possible to include it in the g2 function?

Thanks.
Zak

P.S. Also it prints "Missing xxxx" whenever one runs the timetrace and g2 function. Maybe it should be removed?

**Comment by GCBallesteros** [comment]
Hi @zak489,

That should be doable.

The missing xxxx happens when a few records at the very end are skipped this allows for simpler and faster code. In the big scheme of things skipping a 1k records on a file with several billions records is worth the tradeoff. I agree that it would be preferable is that could muted to avoid random messages printing.

**Comment by GCBallesteros** [comment]
@zak489  The new feature is now implemented. Please have a look at the examples/g2.py to check how to use it.
