### ISSUE TITLE
Zero counts in timetrace when count rates are low

### ISSUE THREAD

**Issue by fbbarnes** [GCBallesteros/trattoria#4]
I have an issue where the timetrace function returns an empty array for ptu files with low count rates. 

For example, I have a 10 second T3 ptu file with ~1000 records according to the header (in agreement with HydraHarp software count rate of ~100Hz) but the timetrace result is empty. I have tested this with resolutions ranging from 1s to 1ps. Opening the file in HydraHarp software shows there are records (when analysed as histogram). The trattoria code seems to work fine with files with higher count rates.

Please could you let me know if it is possible this is due to trattoria?

**Comment by GCBallesteros** [comment]
Trattoria is only a thin wrapper around [ttr-toolbox](https://github.com/GCBallesteros/tttr-toolbox) so my expectation is that if there is a problem it will be there.

It's been quite some time since I look at this code but I can try to make some space to work on it. I would need some file for testing though, would you mind sharing the when you are talking about? If so you could send it to __myfirstname__@[maxwellrules.com](http://maxwellrules.com/about.html). I would expect a 1000 records to be a tiny file.

**Comment by fbbarnes** [comment]
Hi, thank you very much for your quick reply! I have sent over the file.

**Comment by GCBallesteros** [comment]
I think I have found the error (but not verified it yet).

In the code for the ttr-toolbox I use the [read_u32_into](https://netvl.github.io/immeta/byteorder/trait.ReadBytesExt.html#method.read_u32_into) function here:
- https://github.com/GCBallesteros/tttr-toolbox/blob/cc453b48e891d285873d91f14f1e9dfda6b8c4ed/tttr-toolbox/src/parsers/ptu/streamers.rs#L234 (for HHT3_HH2)
- https://github.com/GCBallesteros/tttr-toolbox/blob/cc453b48e891d285873d91f14f1e9dfda6b8c4ed/tttr-toolbox-proc-macros/src/lib.rs#L125 (for the other filetypes supported)

That function fails if it doesn't manage to read enough records to __completely__ fill  a preallocated buffer. The size of the preallocated buffer is rather big right now ( [1024 * 16](https://github.com/GCBallesteros/tttr-toolbox/blob/cc453b48e891d285873d91f14f1e9dfda6b8c4ed/tttr-toolbox/src/parsers/ptu/streamers.rs#L1) ) for performance reasons. The goal is to minimize how many times we have to issue system calls to read from the hard drive by reading big chunks of the file each time.

The downside to this is that it is highly likely that the last chunk of records will be skipped unless the number of records in the file is exactly divisible by 1024 * 16 (probability close to zero).  Since your file has 1000 < 1024*16 records they all get ignored. My assumption here was that in real-life experiments ignoring such a small number of events wouldn't be important,  but I might well be wrong.

I will try to look for a performant solution but I hope that in the mean time you are satisfied with this answer. 

If I may, could you let your experiment run for approximately  a bit more than 10 \*16 = 160 seconds (e.g. 200 seconds) so that by the end of it you have more than 1024\*16=16384 records and try again?

pls don't close this issue. I will pin it so that future confused users can easily find it

**Comment by fbbarnes** [comment]
Hi, I have sent you some ptu files.

One file was collected over 12s and has 16331 (<16\*1024) records, and the timetrace function returns zero counts. Another file was collected over 13s and has 17653 (>16\*1024) records, and the timetrace returns non zero counts. 

From this data, it seems you have the correct explanation.

**Comment by GCBallesteros** [comment]
This issue has been corrected in the latest version of Trattoria and associated libraries.
