### ISSUE TITLE
Is there a quick and simple way to simply get the time-tagged photon arrival events?

### ISSUE THREAD

**Issue by AlbertVong** [GCBallesteros/trattoria#5]
Thanks for making this tool.

Is there a simple way to extract the time-tagged photon arrival events for a given ptu file in T2 mode? Specifically, just an array with all the arrival times for each photon.

I was trying to get that via the timetrace function (with resolution exactly at the measurement resolution, e.g. 16 ps) but the resulting time trace doesn't seem to reflect the actual photon arrival times. For example, when using a resolution of 16 ps, the time array only goes up to a value of 0.6 ms when the experiment took 900 s to run.

**Comment by GCBallesteros** [comment]
The short answer is no. Although it could definitely be implemented if you are not in a big hurry as my personal circumstances don't allow me much time for this projects as they are now far removed from professional life.

# Explanation

Now for a slightly longer explanation of the behaviour you are observing.

The data for each event is stored in 32 bits records, 25 of which are reserved for the actual time. Each does not store directly a timestamp, instead it stores how much time has passed since the last overflow record (a special time of event) in units of the time resolution, each tick is 16 ps. The overflow record happens every 0.6 ms. Why 0.6 ms? Well in 25 bits you can store `2^25` ticks before you run out of space and that times 16 picoseconds is 0.6 ms.

The behaviour you are seeing is an interaction between the design of the file format and the current implementation both of which are reasonable. The file format is a compromise between how much space it takes to store the data which can grow pretty big and what is the longest time until you get an overflow record. On the other hand the library is optimized for speed and limiting memory in order to achieve this in a straightforward manner it inherited that "limitation" from the file format.

As a side note, the timetrace you are requesting would have 900 s/16 ps = 56_250_000_000_000 points at say one byte per point that would require using uint8 __56 TB of RAM__ just to store the time trace!

# A possible solution

Exporting and storing the timestamps as uint64 would allow to record unique timestamps for up to 82k hours. The size of the output file could potential grow to the Petabytes for an experiment of 900 s. In this case one would have to pass some limit to the max number of records that can be out or a time limit in the low number of seconds range.

This is doable but I don't know how compatible your timescales are with mine. I'm thinking a couple of months or so.

# Problem reframing

99.9% of the time one is not interested in the actual time of arrival of the events but at some derived quantity or statistic. May I ask what is ultimately the reason for wanting the exact time of arrivals? Maybe I can help finding an alternative approach to your data processing needs.

**Comment by tpoint75** [comment]
Just look, take the Unfold class:
https://picoquant.github.io/snAPI/snAPI.Main.html#snAPI_Main_Unfold_getData

This is how the code can looks like for a ptu-File with T2 data:
https://github.com/PicoQuant/snAPI/blob/main/tools/Tool_ReadPTU.py

**Comment by GCBallesteros** [comment]
Thanks @tpoint75 that should do the trick! Please still keep in mind that for any sizable amount of counts and experiment duration this is going to produce a LOT of data and that, unless the end goal is to just get the click times, there is often a better way.

**Comment by GCBallesteros** [comment]
@AlbertVong Are you happy with the solution from @tpoint75 so that I can close this issue?

**Comment by AlbertVong** [comment]
Yes, sorry for the late reply! This is perfect and exactly what I was looking for. Sorry for being a bit vague (I was looking for the relative delay times between arrival events (what tpoint75 suggested is what I'm lookin for). Thanks again for the quick response.
